[metadata]
name = influence-prototype
version = 0.0.1
description = Various prototypes for computing influence functions
url = https://github.com/pomonam/influence-prototype/
license = Apache 2.0
long_description = file: README.md
long_description_content_type = text/markdown
keywords = machine-learning, deep-learning, influence-functions
platforms = any
classifiers =
  Development Status :: 3 - Alpha
  Intended Audience :: Developers
  Intended Audience :: Science/Research
  License :: OSI Approved :: Apache Software License
  Operating System :: OS Independent
  Programming Language :: Python :: 3.7
  Programming Language :: Python :: 3.8
  Programming Language :: Python :: 3.9
  Programming Language :: Python :: 3.10
  Topic :: Scientific/Engineering :: Artificial Intelligence

[options]
zip_safe = False
packages = find:
include_package_data = True
setup_requires =
  setuptools_scm
# Dependencies of the project:
install_requires =
  isort==5.12.0
  pylint==2.17.5
  pytest==7.4.2
  black==23.9.1
  tqdm==4.66.1
  wget==3.2
  pre-commit==3.4.0
  numpy==1.26.0
  pandas==2.1.1
  scikit_learn==1.3.0
  ucimlrepo==0.0.1
  traker==0.2.1
  transformers==4.33.2
  accelerate==0.23.0
  datasets==2.14.5
  evaluate==0.4.0
python_requires = >=3.9

###############################################################################
#                           Additional Dependencies                           #
###############################################################################
[options.extras_require]
# PyTorch CPU
pytorch_cpu =
  torch==2.1.0
  torchvision==0.16.0

# PyTorch GPU
pytorch_gpu =
  torch==2.1.0+cu118
  torchvision==0.16.0+cu118

###############################################################################
#                           Linting Configurations                            #
###############################################################################
[isort]
profile=black

[pylint.MASTER]
persistent=no
[pylint.REPORTS]
reports=no
msg-template={msg_id}:{line:3} {obj}: {msg} [{symbol}]
[pylint.'MESSAGES CONTROL']
enable=indexing-exception,old-raise-syntax
[pylint.BASIC]
no-docstring-rgx=(__.*__|main)
docstring-min-length=10
module-rgx=^(_?[a-z][a-z0-9_]*)|__init__$
const-rgx=^(_?[A-Z][A-Z0-9_]*|__[a-z0-9_]+__|_?[a-z][a-z0-9_]*)$
class-attribute-rgx=^(_?[A-Z][A-Z0-9_]*|__[a-z0-9_]+__|_?[a-z][a-z0-9_]*)$
class-rgx=^_?[A-Z][a-zA-Z0-9]*$
function-rgx=^(?:(?P<exempt>setUp|tearDown|setUpModule|tearDownModule)|(?P<camel_case>_?[A-Z][a-zA-Z0-9]*)|(?P<snake_case>_?[a-z][a-z0-9_]*))$
method-rgx=(?x)
  ^(?:(?P<exempt>_[a-z0-9_]+__|runTest|setUp|tearDown|setUpTestCase
         |tearDownTestCase|setupSelf|tearDownClass|_testDatasetSize|setUpClass
         |(test|assert)_*[A-Z0-9][a-zA-Z0-9_]*|next)
     |(?P<camel_case>_{0,2}[A-Z][a-zA-Z0-9_]*)
     |(?P<snake_case>_{0,2}[a-z][a-z0-9_]*))$
attr-rgx=^_{0,2}[a-z][a-z0-9_]*$
argument-rgx=^[a-z][a-z0-9_]*$
variable-rgx=^[a-z][a-z0-9_]*$
inlinevar-rgx=^[a-z][a-z0-9_]*$
good-names=main,_
bad-names=
property-classes=abc.abstractproperty
[pylint.TYPECHECK]
ignore-mixin-members=yes
contextmanager-decorators=contextlib.contextmanager,contextlib2.contextmanager
[pylint.VARIABLES]
init-import=no
dummy-variables-rgx=^\*{0,2}(_$|unused_|dummy_)
[pylint.CLASSES]
defining-attr-methods=__init__,__new__,setUp
valid-classmethod-first-arg=cls,class_
[pylint.EXCEPTIONS]
overgeneral-exceptions=
  builtins.StandardError,
  builtins.Exception,
  builtins.BaseException
[pylint.IMPORTS]
deprecated-modules=regsub,TERMIOS,Bastion,rexec,sets
[pylint.FORMAT]
disable=
  abstract-method,
  access-member-before-definition,
  broad-except,arguments-differ,
  assignment-from-no-return,
  attribute-defined-outside-init,
  bad-mcs-classmethod-argument,
  bad-option-value,c-extension-no-member,
  consider-merging-isinstance,
  consider-using-dict-comprehension,
  consider-using-enumerate,consider-using-in,
  consider-using-set-comprehension,
  consider-using-ternary,
  deprecated-method,
  design,
  file-ignored,
  fixme,
  global-statement,
  import-error,
  inconsistent-return-statements,
  invalid-unary-operand-type,
  len-as-condition,
  locally-disabled,
  locally-enabled,
  misplaced-comparison-constant,
  missing-docstring,multiple-imports,
  no-else-return,
  no-member,
  no-name-in-module,
  no-self-use,
  no-value-for-parameter,
  not-an-iterable,
  not-context-manager,
  pointless-except,
  protected-access,
  redefined-argument-from-local,
  signature-differs,
  similarities,
  simplifiable-if-expression,
  star-args,
  super-init-not-called,
  suppressed-message,
  too-many-function-args,
  trailing-comma-tuple,
  trailing-newlines,
  ungrouped-imports,
  unnecessary-pass,
  unsubscriptable-object,
  unused-argument,
  useless-object-inheritance,
  useless-return,
  useless-suppression,
  wrong-import-order,
  wrong-import-position,
  unneeded-not,
  unexpected-keyword-arg,
  redundant-keyword-arg,
  unspecified-encoding,
  logging-fstring-interpolation,
  consider-using-f-string,
  consider-using-generator,
  logging-format-interpolation,
  import-outside-toplevel,
  consider-using-from-import,
  line-too-long,
  unused-import,
  unused-variable,
  redefined-outer-name,
  unbalanced-tuple-unpacking,
  anomalous-backslash-in-string,
  dangerous-default-value,
  invalid-name,
max-line-length=100
ignore-long-lines=(?x)
  (^\s*(import|from)\s
   |^\s*(\#\ )?<?(https?|ftp):\/\/[^\s\/$.?#].[^\s]*>?$
   |^[a-zA-Z_][a-zA-Z0-9_]*\s*=\s*("[^"]\S+"|'[^']\S+')
   )
max-module-lines=99999
indent-string='    '
single-line-if-stmt=y
[pylint.LOGGING]
logging-modules=logging,absl.logging
[pylint.MISCELLANEOUS]
indent-after-paren=4